apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-nfs-server-provisioner-0
spec:
  capacity:
    storage: 400Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /srv/nfs
  claimRef:
    namespace: nfs-server-provisioner
    name: data-nfs-server-provisioner-0