fullnameOverride: hive-metastore

metastore:
  replicas: 1

  image: ssup2/hive-postgres:4.0.1
  imagePullSecret: ""

  schema:
    init: true
    dbType: postgres

  config: |
    <configuration>
      <property>
        <name>javax.jdo.option.ConnectionURL</name>
        <value>jdbc:postgresql://postgresql.postgresql.svc:5432/metastore</value>
        <description>JDBC connect string for a JDBC metastore</description>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionDriverName</name>
        <value>org.postgresql.Driver</value>
        <description>Driver class name for a JDBC metastore</description>
    </property>
    <property>
        <name>javax.jdo.option.ConnectionUserName</name>
        <value>postgres</value>
        <description>Username to use against metastore database</description>
    </property>
    <property>
        <name>javax.jdo.option.ConnectionPassword</name>
        <value>root123!</value>
        <description>Password to use against metastore database</description>
    </property>
    </configuration>

  nodeSelector:
    node-group.dp.ssup2: "storage"
