apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zincsearch.fullname" . }}
  labels:
    {{- include "zincsearch.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: "{{ .Values.auth.username }}"
  password: "{{ .Values.auth.password }}"
