apiVersion: v1
kind: Service
metadata:
  name: {{ include "ranger.fullname" . }}
  labels:
    {{- include "ranger.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 6088
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "ranger.selectorLabels" . | nindent 4 }}
