apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: hive-metastore
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: hive-metastore
  template:
    metadata:
      labels:
        app: hive-metastore
    spec:
      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      {{- end }}
      containers:
        - name: metastore
          image: {{ .Values.image }}
          env:
            - name: SERVICE_NAME
              value: "metastore"
            - name: DB_DRIVER
              value: {{ .Values.schema.dbType }}
            - name: IS_RESUME
              value: "true"
          volumeMounts:
            - name: hive-cfg
              mountPath: /opt/hive/conf/hive-site.xml
              subPath: hive-site.xml
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
        
      volumes:
        - name: hive-cfg
          configMap:
            name: hive-metastore-config
