apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: hive-metastore-config
  labels:
    app: hive-metastore
data:
  hive-site.xml: {{- toYaml .Values.config | nindent 2 }}
