{{- if .Values.schema.init }}
apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ .Release.Namespace }}
  name: hive-metastore-initschema
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      {{- end }}
      containers:
        - name: init-schema
          image: {{ .Values.image }}
          command: [
            "/opt/hive/bin/schematool", "--verbose", "-initSchema", "-dbType", {{ .Values.schema.dbType }}
          ]
          volumeMounts:
            - name: hive-cfg
              mountPath: /opt/hive/conf/hive-site.xml
              subPath: hive-site.xml
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      volumes:
        - name: hive-cfg
          configMap:
            name: hive-metastore-config
{{- end }}
